all:
  children:
    splunk_instance:
      hosts:
        ns-daldb-splunk-hf01.netsync.com:
          ansible_host: 192.168.7.244
          ansible_user: netsyncadmin
        ns-daldb-splunk-hf02.netsync.com:
          ansible_host: 192.168.7.245
          ansible_user: netsyncadmin
        # ns-daldb-splunk-ix01.netsync.com:
        #   ansible_host: ns-daldb-splunk-ix01.netsync.com
        #   ansible_user: netsyncadmin
        # ns-daldb-splunk-ix02.netsync.com:
        #   ansible_host: ns-daldb-splunk-ix02.netsync.com
        #   ansible_user: netsyncadmin
        # ns-daldb-splunk-ix03.netsync.com:
        #   ansible_host: ns-daldb-splunk-ix03.netsync.com
        #   ansible_user: netsyncadmin
        # ns-daldb-splunk-sh01.netsync.com:
        #   ansible_host: ns-daldb-splunk-sh01.netsync.com
        #   ansible_user: netsyncadmin
        # ns-daldb-splunk-sh02.netsync.com:
        #   ansible_host: ns-daldb-splunk-sh02.netsync.com
        #   ansible_user: netsyncadmin
        # ns-daldb-splunk-sh03.netsync.com:
        #   ansible_host: ns-daldb-splunk-sh03.netsync.com
        #   ansible_user: netsyncadmin
