all:
  children:
    splunk_instance:
      hosts:
        ns-daldb-splunk-hf01:
          ansible_host: 192.168.7.244
          ansible_user: netsyncadmin
        ns-daldb-splunk-hf02:
          ansible_host: 192.168.7.245
          ansible_user: netsyncadmin
