all:
  children:
    heavyforwarders:
      hosts:
        hf01:
          ansible_host: 192.168.7.244
          ansible_user: admin
    searchheads:
      hosts: 
        sh01:
          ansible_host: 192.168.7.245
          ansible_user: admin
    indexers:
      hosts: {}
    cluster_managers:
      hosts: {}
    deployers:
      hosts: {}
    license_managers:
      hosts: {}
    monitoring_consoles:
      hosts: {}
    deployment_servers:
      hosts: {}
    splunk_instance:
      children:
        heavyforwarders:
        searchheads:
        indexers:
        cluster_managers:
        deployers:
        license_managers:
        monitoring_consoles:
        deployment_servers:
